name: Deploy to the server PR

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          if ! [ -d pr/${{ github.event.pull_request.number }} ]; then git clone git@github.com:teamdevm/team-project-buses.git pr/${{ github.event.pull_request.number }}; fi
          git -C pr/${{ github.event.pull_request.number }} fetch
          git -C pr/${{ github.event.pull_request.number }} checkout origin/${{ github.head_ref }}
